CREATE TABLE perfil (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    CONSTRAINT uk_perfil_nome UNIQUE (nome)
);

CREATE TABLE usuario (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    senha         VARCHAR(255) NOT NULL,
    telefone      VARCHAR(20),
    status        BOOLEAN      NOT NULL DEFAULT TRUE,
    data_criacao  TIMESTAMP    NOT NULL DEFAULT now(),
    ultimo_acesso TIMESTAMP,
    perfil_id     INTEGER      NOT NULL,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_perfil FOREIGN KEY (perfil_id)
        REFERENCES perfil (id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX idx_usuario_perfil_id ON usuario (perfil_id);
