CREATE TABLE cliente (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150)   NOT NULL,
    cpf             VARCHAR(11)    NOT NULL,
    email           VARCHAR(150),
    telefone        VARCHAR(20),
    data_nascimento DATE,
    limite_credito  DECIMAL(12,2)  DEFAULT 0,
    observacoes     TEXT,
    status          BOOLEAN        NOT NULL DEFAULT TRUE,
    data_criacao    TIMESTAMP      NOT NULL DEFAULT now(),
    CONSTRAINT uk_cliente_cpf UNIQUE (cpf),
    CONSTRAINT ck_cliente_limite_credito CHECK (limite_credito >= 0)
);

CREATE TABLE endereco (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  INTEGER      NOT NULL,
    tipo        VARCHAR(30),
    cep         VARCHAR(8)   NOT NULL,
    logradouro  VARCHAR(150) NOT NULL,
    numero      VARCHAR(20)  NOT NULL,
    complemento VARCHAR(100),
    bairro      VARCHAR(100) NOT NULL,
    cidade      VARCHAR(100) NOT NULL,
    estado      VARCHAR(2)   NOT NULL,
    CONSTRAINT fk_endereco_cliente FOREIGN KEY (cliente_id)
        REFERENCES cliente (id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE INDEX idx_endereco_cliente_id ON endereco (cliente_id);
