CREATE TABLE "perfil" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "telefone" varchar(20),
  "status" boolean NOT NULL DEFAULT true,
  "data_criacao" timestamp NOT NULL,
  "ultimo_acesso" timestamp,
  "perfil_id" integer NOT NULL
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "email" varchar(150),
  "telefone" varchar(20),
  "data_nascimento" date,
  "limite_credito" decimal(12,2) DEFAULT 0,
  "observacoes" text,
  "status" boolean NOT NULL DEFAULT true,
  "data_criacao" timestamp NOT NULL
);

CREATE TABLE "endereco" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer NOT NULL,
  "tipo" varchar(30),
  "cep" varchar(8) NOT NULL,
  "logradouro" varchar(150) NOT NULL,
  "numero" varchar(20) NOT NULL,
  "complemento" varchar(100),
  "bairro" varchar(100) NOT NULL,
  "cidade" varchar(100) NOT NULL,
  "estado" varchar(2) NOT NULL
);

CREATE TABLE "categoria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "descricao" text,
  "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "produto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoria_id" integer NOT NULL,
  "nome" varchar(150) NOT NULL,
  "codigo_interno" varchar(50) UNIQUE NOT NULL,
  "codigo_barras" varchar(50) UNIQUE,
  "descricao" text,
  "unidade_medida" varchar(10) NOT NULL,
  "preco_custo" decimal(12,2) NOT NULL,
  "preco_venda" decimal(12,2) NOT NULL,
  "estoque_minimo" decimal(12,3) DEFAULT 0,
  "estoque_maximo" decimal(12,3),
  "imagem" varchar(255),
  "status" boolean NOT NULL DEFAULT true
);

CREATE TABLE "servico" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(150) NOT NULL,
  "codigo_interno" varchar(50) UNIQUE NOT NULL,
  "descricao" text,
  "preco_custo" decimal(12,2) DEFAULT 0,
  "preco_venda" decimal(12,2) NOT NULL,
  "status" boolean NOT NULL DEFAULT true,
  "data_criacao" timestamp NOT NULL
);

CREATE TABLE "estoque" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produto_id" integer UNIQUE NOT NULL,
  "quantidade" decimal(12,3) NOT NULL DEFAULT 0,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "movimentacao_estoque" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produto_id" integer NOT NULL,
  "tipo" varchar(20) NOT NULL,
  "quantidade" decimal(12,3) NOT NULL,
  "origem" varchar(30) NOT NULL,
  "origem_id" integer,
  "data_movimentacao" timestamp NOT NULL,
  "observacao" text
);

CREATE TABLE "fornecedor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(2) NOT NULL,
  "documento" varchar(14) UNIQUE NOT NULL,
  "razao_social" varchar(150) NOT NULL,
  "nome_fantasia" varchar(150),
  "email" varchar(150),
  "telefone" varchar(20),
  "dados_bancarios" text,
  "observacoes" text,
  "status" boolean NOT NULL DEFAULT true,
  "data_criacao" timestamp NOT NULL
);

CREATE TABLE "produto_fornecedor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produto_id" integer NOT NULL,
  "fornecedor_id" integer NOT NULL,
  "codigo_fornecedor" varchar(50),
  "preco_custo" decimal(12,2),
  "principal" boolean NOT NULL DEFAULT false
);

CREATE TABLE "compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fornecedor_id" integer NOT NULL,
  "data_compra" timestamp NOT NULL,
  "status" varchar(20) NOT NULL,
  "desconto" decimal(12,2) DEFAULT 0,
  "total" decimal(12,2) NOT NULL,
  "forma_pagamento" varchar(30),
  "observacoes" text
);

CREATE TABLE "item_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compra_id" integer NOT NULL,
  "produto_id" integer,
  "servico_id" integer,
  "quantidade" decimal(12,3) NOT NULL,
  "preco_unitario" decimal(12,2) NOT NULL,
  "desconto" decimal(12,2) DEFAULT 0,
  "subtotal" decimal(12,2) NOT NULL
);

CREATE TABLE "venda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" integer,
  "data_venda" timestamp NOT NULL,
  "status" varchar(20) NOT NULL,
  "desconto" decimal(12,2) DEFAULT 0,
  "total" decimal(12,2) NOT NULL,
  "forma_pagamento" varchar(30),
  "observacoes" text
);

CREATE TABLE "item_venda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venda_id" integer NOT NULL,
  "produto_id" integer,
  "servico_id" integer,
  "quantidade" decimal(12,3) NOT NULL,
  "preco_unitario" decimal(12,2) NOT NULL,
  "desconto" decimal(12,2) DEFAULT 0,
  "subtotal" decimal(12,2) NOT NULL
);

CREATE TABLE "movimento_financeiro" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(20) NOT NULL,
  "descricao" varchar(200) NOT NULL,
  "valor" decimal(12,2) NOT NULL,
  "data_lancamento" timestamp NOT NULL,
  "data_vencimento" date,
  "data_pagamento" date,
  "status" varchar(20) NOT NULL,
  "forma_pagamento" varchar(30),
  "origem" varchar(30),
  "origem_id" integer,
  "observacoes" text
);

CREATE TABLE "endereco_fornecedor" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fornecedor_id" integer NOT NULL,
  "tipo" varchar(30),
  "cep" varchar(8) NOT NULL,
  "logradouro" varchar(150) NOT NULL,
  "numero" varchar(20) NOT NULL,
  "complemento" varchar(100),
  "bairro" varchar(100) NOT NULL,
  "cidade" varchar(100) NOT NULL,
  "estado" varchar(2) NOT NULL
);

CREATE UNIQUE INDEX ON "produto_fornecedor" ("produto_id", "fornecedor_id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("perfil_id") REFERENCES "perfil" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "endereco" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produto" ADD FOREIGN KEY ("categoria_id") REFERENCES "categoria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produto" ADD FOREIGN KEY ("id") REFERENCES "estoque" ("produto_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movimentacao_estoque" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produto_fornecedor" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "produto_fornecedor" ADD FOREIGN KEY ("fornecedor_id") REFERENCES "fornecedor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compra" ADD FOREIGN KEY ("fornecedor_id") REFERENCES "fornecedor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_compra" ADD FOREIGN KEY ("compra_id") REFERENCES "compra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_compra" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_compra" ADD FOREIGN KEY ("servico_id") REFERENCES "servico" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venda" ADD FOREIGN KEY ("cliente_id") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_venda" ADD FOREIGN KEY ("venda_id") REFERENCES "venda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_venda" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_venda" ADD FOREIGN KEY ("servico_id") REFERENCES "servico" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "endereco_fornecedor" ADD FOREIGN KEY ("fornecedor_id") REFERENCES "fornecedor" ("id") DEFERRABLE INITIALLY IMMEDIATE;
